# SPDX-License-Identifier: Apache-2.0
version: "2" # v3 does not support 'extends' yet
services:
  ca-base:
    image: hyperledger/fabric-ca:${HLF_VERSION}
    expose:
      - ${CA_PORT}
    environment:
      - FABRIC_CA_HOME=${FABRIC_CA_HOME}
      - FABRIC_CA_SERVER_PORT=${CA_PORT}
      #- FABRIC_CA_SERVER_TLS_ENABLED=false
    command: /bin/bash -c 'fabric-ca-server start -b ${CA_ADMIN_ID}:${CA_ADMIN_PASSWD} -d --cfg.affiliations.allowremove --cfg.identities.allowremove'
    # --boot (bootstrap identity) option is required for init when LDAP is disabled. build default config file
    # --cafiles ${FABRIC_CA_HOME}/fabric-ca-server-config.yaml

  tls-ca-base:
    image: hyperledger/fabric-ca:${HLF_VERSION}
    expose:
      - ${CA_PORT}
    environment:
      - FABRIC_CA_HOME=${FABRIC_CA_HOME}
      - FABRIC_CA_SERVER_PORT=${CA_PORT}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    command: /bin/bash -c 'fabric-ca-server start -b ${CA_ADMIN_ID}:${CA_ADMIN_PASSWD} -d --cfg.affiliations.allowremove --cfg.identities.allowremove'
    # -b (bootstrap identity) option is required for init when LDAP is disabled.
    # -c ${FABRIC_CA_HOME}/fabric-ca-server-config.yaml
