version: "2" # v3 does not support 'extends' yet

networks:
    frontend-net:
        external: true
    backend-net:

volumes:
    web-static:
    react-workdir:

services:
    react-develop:
        image: react:centos7
        build:
            shm_size: '1GB'
            context: ../dockerfiles/in-docker-compose
            dockerfile: build_react
        volumes:
            - ${HOST_WORK_DIR}/reactapp:${REACT_WORK_DIR}
            - ${HOST_WORK_DIR}/web-static:${REACT_STATIC_DIR}
        networks:
            - frontend-net
            - backend-net
        external_links:
            - nodeweb
            - django
            - jupyter
        ports:
            - ${PORT_HTTP}:${PORT_HTTP}
            - ${PORT_HTTPS}:${PORT_HTTPS}
        expose:
            - ${PORT_NGINX}
        cap_drop:
          - ALL
        cap_add:
          - NET_BIND_SERVICE
        working_dir: ${REACT_WORK_DIR}
        entrypoint: /bin/bash
        command: npm start



