version: "2" # v3 does not support 'extends' yet

networks:
  frontend-net:
    external: true
  backend-net:

volumes:
  web-static:

services:
  nginx-base:
    image: nginx:centos7
    build:
      shm_size: "1GB"
      context: ../dockerfiles
      dockerfile: build_nginx
      args: # allocate value to ARG vars in Dockerfile
        - appuser=${CONTAINER_USER}
        - appgroup=${CONTAINER_GROUP}
        - workingdir=${NGINX_CFG_DIR}
        - staticdir=${NGINX_STATIC_DIR}
    networks:
      - frontend-net
      - backend-net
    external_links:
      - nodeweb
      - django
      - jupyter
      - elastic
    ports:
      - ${PORT_HTTP}:${PORT_HTTP}
      - ${PORT_HTTPS}:${PORT_HTTPS}
    expose:
      - ${PORT_FRONTEND}
    working_dir: ${NGINX_CFG_DIR}
    entrypoint: ${NGINX_CFG_DIR}

  nginx-develop:
    extends: nginx-base
    tty: true
    cap_drop:
      - MAC_ADMIN
      - NET_ADMIN
      - SYS_ADMIN
    cap_add:
      - ALL
    group_add:
      - ${CONTAINERS_GROUP} #to rw on same Host File(소유권한 그룹)
    volumes:
      - ${HOST_WORK_DIR}/nginx:${NGINX_CFG_DIR}
      - ${HOST_WORK_DIR}/nginx/logs:${NGINX_LOG_DIR}
      - ${HOST_WORK_DIR}/web-static:${NGINX_STATIC_DIR}

  nginx-product:
    extends: nginx-base
    #        security_opt:
    #          - label:user:USERNAME #labeling scheme for each container
    #          - label:role:ROLENAME #labeling scheme for each container
    tty: false
    read_only: true
    privileged: false
    user: nginx
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ${NGINX_CFG_DIR}:ro
      - ${NGINX_LOG_DIR}:ro
      - web-static:${NGINX_STATIC_DIR}:rw

  nginx-helper:
    image: ubuntu:latest
    cap_drop:
      - MAC_ADMIN
      - NET_ADMIN
      - SYS_ADMIN
    cap_add:
      - ALL
    networks:
      - frontend-net
    ports:
      - ${PORT_FRONTEND}:${PORT_FRONTEND}
    tty: true
    volumes_from:
      - nginx-product:${NGINX_CFG_DIR}
      - nginx-product:${NGINX_LOG_DIR}
      - nginx-product:${NGINX_STATIC_DIR}
    working_dir: ${NGINX_CFG_DIR}
    entrypoint: "/bin/sh"
