# Depends on the hyperledger/fabric-orderer image.

version: "2"

services:
  orderer-base:
    image: hyperledger/fabric-orderer:${HLF_VERSION}
    expose:
      - ${ORDERER_PORT}
    environment:
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC}
      # listen addr:port
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${ORDERER_PORT}
      # MSP
      - ORDERER_GENERAL_LOCALMSPID=${ORDMSP}
      - ORDERER_GENERAL_LOCALMSPDIR=${ORDERER_HOME}/msp
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_BATCHTIMEOUT=2s
      - ORDERER_GENERAL_MAXMESSAGECOUNT=10
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      # must be file type in production
      - ORDERER_GENERAL_LEDGERTYPE=file
      # genesis block : provisional(with GenesisProfile), file(with GenesisFile)
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=${ORDERER_HOME}/${CHANNEL_ARTIFACTS}/${ORDERER_GENSIS}
      - ORDERER_GENERAL_GENESISPROFILE=${SYSTEM_CHANNEL_PROFILE}
      - ORDERER_GENERAL_SYSTEMCHANNEL=${SYSTEM_CHANNEL_ID}
      - ORDERER_GENERAL_ORDERERTYPE=etcdraft
      # must enabled TLS for etcdraft
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER_HOME}/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER_HOME}/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[${ORDERER_HOME}/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=${ORDERER_HOME}/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=${ORDERER_HOME}/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[${ORDERER_HOME}/tls/ca.crt]
    working_dir: ${ORDERER_HOME}
    command: orderer
