version: "2" # v3 does not support 'extends' yet

networks:
  backend-net:

volumes:
  web-static:
  data-jupyter:

services:
  jupyter-base:
    image: jupyter:centos7
    build:
      shm_size: "1GB"
      context: ../dockerfiles
      dockerfile: build_jupyter
      args: # allocate value to ARG vars in Dockerfile
        - appuser=${CONTAINER_USER}
        - appgroup=${CONTAINER_GROUP}
        - workingdir=${WORKING_DIR}
    networks:
      - backend-net
    working_dir: ${WORKING_DIR}
    entrypoint: "/bin/sh"

  jupyter-develop:
    extends: jupyter-base
    cap_drop:
      - MAC_ADMIN
      - NET_ADMIN
      - SYS_ADMIN
    cap_add:
      - ALL
    ports:
      - ${PORT_JUPYTER}:${PORT_JUPYTER}
    volumes:
      - ${HOST_WORK_DIR}/jupyter/data:${JUPYTER_DATA_DIR}:rw
      - ${HOST_WORK_DIR}/jupyter/runtime:${JUPYTER_RUNTIME_DIR}:rw
      - ${HOST_WORK_DIR}/jupyter/cfg:${JUPYTER_CFG_DIR}:rw
      - ${HOST_WORK_DIR}/jupyter/app:${WORKING_DIR}:rw
    command:
      - "jupyter lab --ip ${IP_ALLOWED} --port ${PORT_JUPYTER} --no-browser --core-mode --log-level='INFO' &"

  jupyter-product:
    extends: jupyter-base
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - ${PORT_HTTP}:${PORT_HTTP}
      - ${PORT_HTTPS}:${PORT_HTTPS}
    expose:
      - ${PORT_JUPYTER}
    volumes:
      - data-jupyter:${WORKING_DIR}:rw
    command:
      - "jupyter lab --ip ${IP_ALLOWED} --port ${PORT_HTTPS} --app-dir=${WORKING_DIR} --no-browser --log-level='WARN' &"
