version: "2" # v3 does not support 'extends' yet
networks:
    backend-net:
volumes:
    jupyter-cfg:
    jupyter-data:
    jupyter-runtime:
services:
    jupyter-base:
        image: jupyter:centos7
        build:
            shm_size: '1GB'
            context: ../dockerfiles/in-docker-compose
            dockerfile: build_jupyter
        networks:
            - backend-net
        ports:
            - ${PORT_HTTP}:${PORT_HTTP}
            - ${PORT_HTTPS}:${PORT_HTTPS}
        expose:
            - ${PORT_JUPYTER}
        cap_drop:
          - ALL
        cap_add:
          - NET_BIND_SERVICE
        working_dir: ${JUPYTER_DATA_DIR}
        entrypoint: ${JUPYTER_DATA_DIR}
        command: ["jupyter","lab","--port","${PORT_JUPYTER}","--no-browser", "&"]

    jupyter-develop:
        extends: jupyter-base
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        volumes:
            - ${HOST_WORK_DIR}/jupyter/cfg:${JUPYTER_CFG_GLOBAL_DIR}:rw
            - ${HOST_WORK_DIR}/jupyter/data:${JUPYTER_DATA_DIR}:rw
            - ${HOST_WORK_DIR}/jupyter/runtime:${JUPYTER_RUNTIME_DIR}:ro

    jupyter-product:
        extends: jupyter-base
        cap_drop:
          - ALL
        cap_add:
          - NET_BIND_SERVICE
        volumes:
            - jupyter-cfg:${JUPYTER_CFG_GLOBAL_DIR}:ro
            - jupyter-data:${JUPYTER_DATA_DIR}:rw
            - jupyter-runtime:${JUPYTER_RUNTIME_DIR}:ro

    jupyter-helper:
        image: ubuntu:latest
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        tty: true
        networks:
            - backend-net
        expose:
            - ${PORT_WEB_APP}
        volumes_from:
            - jupyter-product:${JUPYTER_CFG_GLOBAL_DIR}
            - jupyter-product:${JUPYTER_DATA_DIR}
            - jupyter-product:${JUPYTER_RUNTIME_DIR}
        working_dir: ${JUPYTER_DATA_DIR}
        entrypoint: ${JUPYTER_DATA_DIR}
