version: "2" # v3 does not support 'extends' yet

networks:
    backend-net:

volumes:
    web-static:
    data-postgres:

services:
    postgres-base:
        image: postgres:latest
        networks:
            - backend-net
        expose:
            - ${PORT_POSTGRES}
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        working_dir: ${POSTGRES_DATA_DIR}

    postgres-develop:
        extends: postgres-base
        tty: true
        cap_add:
            - ALL
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        volumes:
            - ${HOST_WORK_DIR}/data/postgres:${POSTGRES_DATA_DIR}

    postgres-product:
        extends: postgres-base
        tty: false
        read_only: true
        privileged: false
        #        security_opt:
        #          - label:user:USERNAME #labeling scheme for each container
        #          - label:role:ROLENAME #labeling scheme for each container
        user: postgres
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE
        tmpfs:
            #- ${POSTGRES_LOG_DIR}:uid=${CONTAINER_UID},gid=${CONTAINER_GID}
            - /tmp
        volumes:
            - data-postgres:${POSTGRES_DATA_DIR}:ro
            - ${POSTGRES_CFG_DIR}
            - ${POSTGRES_LOG_DIR}

    postgres-helper:
        image: ubuntu:latest
        networks:
            - backend-net
        expose:
            - ${PORT_POSTGRES}
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        tty: true
        volumes_from:
            - postgres-product:${POSTGRES_DATA_DIR}
            - postgres-product:${POSTGRES_CFG_DIR}
            - postgres-product:${POSTGRES_LOG_DIR}
        working_dir: ${POSTGRES_DATA_DIR}
        entrypoint: ${POSTGRES_DATA_DIR}
