version: "2" # v3 does not support 'extends' yet

networks:
    backend-net:

volumes:
    web-static:

services:
    nodeweb-base:
        image: nodeweb:centos7
        build:
            shm_size: '1GB'
            context: ../dockerfiles/in-docker-compose
            dockerfile: build_nodeweb
        networks:
            - backend-net
        expose:
            - ${PORT_WEB_APP}
        working_dir: ${NODEWEB_WORK_DIR}
        entrypoint: ${NODEWEB_WORK_DIR}
        command: ["npm","run","start"]

    nodeweb-develop:
        extends: nodeweb-base
        tty: true
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        volumes:
            - ${HOST_WORK_DIR}/nodeApp:${NODEWEB_WORK_DIR}
            - ${HOST_WORK_DIR}/web-static:${NODEWEB_STATIC_DIR}

    nodeweb-product:
        extends: nodeweb-base
        tty: false
        read_only: true
        privileged: false
        user: nodeweb
        cap_drop:
          - ALL
        cap_add:
          - NET_BIND_SERVICE
        group_add:
            - ${CONTAINERS_GROUP} #to rw on same Host File(소유권한 그룹)
#        security_opt:
#          - label:user:USERNAME #labeling scheme for each container
#          - label:role:ROLENAME #labeling scheme for each container
        volumes:
            - ${NODEWEB_WORK_DIR}:ro
            - web-static:${NODEWEB_STATIC_DIR}:ro

    nodeweb-helper:
        image: ubuntu:latest
        tty: true
        networks:
            - backend-net
        expose:
            - ${PORT_WEB_APP}
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        volumes_from:
            - nodeweb-product:${NODEWEB_WORK_DIR}
        working_dir: ${NODEWEB_WORK_DIR}
        entrypoint: ${NODEWEB_WORK_DIR}

