version: "2" # v3 does not support 'extends' yet
networks:
    backend-net:
volumes:
    jupyter-cfg:
    jupyter-data:
    jupyter-runtime:
services:
    jupyter-base:
        image: jupyter:centos7
        build:
            shm_size: "1GB"
            context: ../dockerfiles/in-docker-compose
            dockerfile: build_jupyter
        networks:
            - backend-net
        working_dir: ${JUPYTER_WORK_DIR}
        entrypoint: "/bin/sh"

    jupyter-develop:
        extends: jupyter-base
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        ports:
            - ${PORT_JUPYTER}:${PORT_JUPYTER}
        volumes:
            - ${HOST_WORK_DIR}/jupyter/data:${JUPYTER_DATA_DIR}:rw
            - ${HOST_WORK_DIR}/jupyter/runtime:${JUPYTER_RUNTIME_DIR}:rw
            - ${HOST_WORK_DIR}/jupyter/cfg:${JUPYTER_CFG_DIR}:rw
            - ${HOST_WORK_DIR}/jupyter/app:${JUPYTER_WORK_DIR}:rw
        command:
            - "jupyter lab --ip 0.0.0.0 --port ${PORT_JUPYTER} --no-browser &"

    jupyter-product:
        extends: jupyter-base
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE
        ports:
            - ${PORT_HTTP}:${PORT_HTTP}
            - ${PORT_HTTPS}:${PORT_HTTPS}
        expose:
            - ${PORT_JUPYTER}
        volumes:
            - ${HOST_WORK_DIR}/jupyter/data:${JUPYTER_DATA_DIR}:ro
            - ${HOST_WORK_DIR}/jupyter/runtime:${JUPYTER_RUNTIME_DIR}:ro
            - ${HOST_WORK_DIR}/jupyter/cfg:${JUPYTER_CFG_DIR}:rw
            - ${HOST_WORK_DIR}/jupyter/app:${JUPYTER_WORK_DIR}:rw
        command:
            - "jupyter notebook --ip 0.0.0.0 --port ${PORT_HTTP} --port ${PORT_HTTPS} --no-browser &"

    jupyter-helper:
        image: ubuntu:latest
        cap_drop:
            - MAC_ADMIN
            - NET_ADMIN
            - SYS_ADMIN
        cap_add:
            - ALL
        tty: true
        networks:
            - backend-net
        expose:
            - ${PORT_WEB_APP}
        volumes_from:
            - jupyter-product:${JUPYTER_CFG_DIR}
            - jupyter-product:${JUPYTER_DATA_DIR}
            - jupyter-product:${JUPYTER_RUNTIME_DIR}
            - jupyter-product:${JUPYTER_WORK_DIR}
        working_dir: ${JUPYTER_WORK_DIR}
        entrypoint: ${JUPYTER_WORK_DIR}
