version: "2" # v3 does not support 'extends' yet
services:
    nginx.atti:
        image: centos
        volumes:
            - web-nginx-conf:/etc/nginx
            - web-static:/static
        ports:
            - ${PORT_HTTPS}:${PORT_HTTPS}
        expose:
            - ${PORT_NGINX}

