version: "2" # v3 does not support 'extends' yet

networks:
    backend-net:

volumes:
    data-mongodb:

services:
    mongodb-base:
        image: mongodb:centos7
        build:
            shm_sie: '1GB'
            context: ../dockerfiles/in-docker-compose
            dockerfile: build_mongodb
        networks:
            - backend-net
        expose:
            - ${PORT_MONGO}
        cap_drop:
          - ALL
        cap_add:
          - NET_BIND_SERVICE

    mongodb-develop:
        extends: mongodb-base
        tty: true
        external_links:
            - django-develop
            - nodeweb-develop
        volumes:
            - ${HOST_WORK_DIR}/data/mongo:${MONGO_DATA_DIR}

    mongodb-product:
        extends: mongodb-base
        tty: false
        read_only: true
        privileged: false
        user: mysql
        security_opt:
          #- label:user:USERNAME #labeling scheme for each container
          #- label:role:ROLENAME #labeling scheme for each container
        external_links:
            - django-product
            - nodeweb-product
        volumes:
            - ${MONGO_DATA_DIR}
            - ${MONGO_CFG_DIR}




