version: "2" # v3 does not support 'extends' yet

######################################################################
services:
  py-sdk-quart:
    image: hlf-sdk-quart:1.0
    tty: true
    environment:
      - CORE_LOGGING_LEVEL=${FABRIC_LOGGING_SPEC}
      - CORE_VM_ENDPOINT=unix:///host${DOCKER_SOCKET}
      - CORE_PEER_TLS_ENABLED=false
    volumes:
      - /var/run:/host/var/run
      #- ../${HLF_NET_NAME}/userInfoWallet:/userInfoWallet
      #- ../${HLF_NET_NAME}/cryptoSuite:/cryptoSuite
      - ../${HLF_NET_NAME}/config/network:${FABRIC_CFG_PATH}
      - ../hlfApp:/${PROJECT_DIR}/hlfApp
      - ../${HLF_NET_NAME}/chaincode:${PROJECT_DIR}/${HLF_NET_NAME}/chaincode
      - ../${HLF_NET_NAME}/channel-artifacts:${PROJECT_DIR}/${HLF_NET_NAME}/channel-artifacts
      - ../${HLF_NET_NAME}/scripts:${PROJECT_DIR}/${HLF_NET_NAME}/scripts
    working_dir: ${PROJECT_DIR}/${HLF_NET_NAME}/scripts
    command: /bin/bash -c './.env; sleep 99999;'
    #./genNetworkConfig.sh; sleep 3; ./genGenesisBlock.sh; sleep 3000'

  py-sdk-cli:
    image: hlf-sdk-cli:1.4.6
    tty: true
    environment:
      - CORE_LOGGING_LEVEL=${FABRIC_LOGGING_SPEC}
      - CORE_VM_ENDPOINT=unix:///host${DOCKER_SOCKET}
      - CORE_PEER_TLS_ENABLED=false
    volumes:
      - /var/run:/host/var/run
      #- ../${HLF_NET_NAME}/userInfoWallet:/userInfoWallet
      #- ../${HLF_NET_NAME}/cryptoSuite:/cryptoSuite
      - ../${HLF_NET_NAME}/config/network:${FABRIC_CFG_PATH}
      - ../hlfApp:/${PROJECT_DIR}/hlfApp
      - ../${HLF_NET_NAME}/chaincode:${PROJECT_DIR}/${HLF_NET_NAME}/chaincode
      - ../${HLF_NET_NAME}/channel-artifacts:${PROJECT_DIR}/${HLF_NET_NAME}/channel-artifacts
      - ../${HLF_NET_NAME}/scripts:${PROJECT_DIR}/${HLF_NET_NAME}/scripts
    working_dir: ${PROJECT_DIR}/${HLF_NET_NAME}/scripts
    command: /bin/bash -c './.env; sleep 99999;'
    #./genNetworkConfig.sh; sleep 3; ./genGenesisBlock.sh; sleep 3000'

  node-sdk-cli:
    image: hlf-cli-npm:2.2.0 #hyperledger/fabric-tools:${HLF_VERSION}
    tty: true
    environment:
      - CORE_LOGGING_LEVEL=${FABRIC_LOGGING_SPEC}
      - CORE_VM_ENDPOINT=unix:///host${DOCKER_SOCKET}
      #- CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_ENABLED=true
    volumes:
      - /var/run:/host/var/run
      #- ../${HLF_NET_NAME}/userInfoWallet:/userInfoWallet
      #- ../${HLF_NET_NAME}/cryptoSuite:/cryptoSuite
      - ../${HLF_NET_NAME}/config/network:${FABRIC_CFG_PATH}
      - ../hlfApp:/${PROJECT_DIR}/hlfApp
      - ../${HLF_NET_NAME}/chaincode:${PROJECT_DIR}/${HLF_NET_NAME}/chaincode
      - ../${HLF_NET_NAME}/channel-artifacts:${PROJECT_DIR}/${HLF_NET_NAME}/channel-artifacts
      - ../${HLF_NET_NAME}/scripts:${PROJECT_DIR}/${HLF_NET_NAME}/scripts
    working_dir: ${PROJECT_DIR}/${HLF_NET_NAME}/scripts
    #command: /bin/bash -c './.env; sleep 99999;'
    #./genNetworkConfig.sh; sleep 3; ./genGenesisBlock.sh; sleep 3000'
