version: 2
networks:
    frontend-net:
        external: true
    backend-net:

volumes:
    web-static:
    data-mongo:

services:
    react-nginx:
        extends:
          file: base-nginx.yaml
          service: nginx-product
        deploy:
		    mode: replicated
		    replicas: 3
		    placement:
			    max_replicas_per_node: 3
		    restart_policy:
			    condition: on-failure
			    failure_action: rollbask
		    resources:
			    limits:
				    cpus: '0.50'
				    memory: 1000M
		    endpoint_mode: vip

    nodeweb:
        extends:
          file: base-nodeweb.yaml
          service: nodeweb-product

	    deploy:
		    mode: replicated
		    replicas: 2
		    update_config:
			    parallelism: 2
			    delay: 10s
		    placement:
			    max_replicas_per_node: 3
		    restart_policy:
			    condition: on-failure
			    failure_action: rollbask
		    resources:
			    limits:
				    cpus: '1.0'
				    memory: 500M
		    endpoint_mode: vip

    mongodb:
        restart: always
        extends:
          file: base-mongodb.yaml
          service: mongodb-product
	    deploy:
		    mode: replicated
		    replicas: 3
		    update_config:
			    parallelism: 2
			    delay: 10s
		    placement:
			    max_replicas_per_node: 3
		    restart_policy:
			    condition: on-failure
			    failure_action: rollbask
		    resources:
			    limits:
				    cpus: '0.30'
				    memory: 500M
		    endpoint_mode: vip


