version: 2
networks:
    frontend-net:
        external: true
    backend-net:

volumes:
    web-static:
    data-mysql:

services:
    nginx-react:
        extends:
          file: base-nginx.yaml
          service: nginx-product
	    deploy:
		    mode: replicated
		    replicas: 3
		    update_config:
			    parallelism: 2
			    delay: 10s
		    placement:
			    max_replicas_per_node: 3
		    restart_policy:
			    condition: on-failure
			    failure_action: rollbask
		    resources:
			    limits:
				    cpus: '0.50'
				    memory: 500M
		    endpoint_mode: vip

    django:
        extends:
          file: base-django.yaml
          service: django-product
	    deploy:
		    mode: replicated
		    replicas: 3
		    update_config:
			    parallelism: 2
			    delay: 10s
		    placement:
			    max_replicas_per_node: 3
		    restart_policy:
			    condition: on-failure
			    failure_action: rollbask
		    resources:
			    limits:
				    cpus: '1.00'
				    memory: 1000M
		    endpoint_mode: vip

    mysql:
        extends:
          file: base-mysql.yaml
          service: mysql-product
	    deploy:
		    mode: replicated
		    replicas: 3
		    update_config:
			    parallelism: 2
			    delay: 10s
		    placement:
			    max_replicas_per_node: 3
		    restart_policy:
			    condition: on-failure
			    failure_action: rollbask
		    resources:
			    limits:
				    cpus: '1.00'
				    memory: 500M
		    endpoint_mode: vip

