version: 2
networks:
    frontend-net:
        external: true
    backend-net:

volumes:
    web-static:
    data-mongo:

x-deploy:
    &deploy-default
    mode: replicated
        replicas: 3
    update_config:
        parallelism: 2
    restart_policy:
        condition: on-failure
        failure_action: rollback
    resources:
        limits:
          cpus: '0.25'
          memory: 3g
          memory-swap: 4g
    endpoint_mode: vip

services:
    react-nginx:
        extends:
          file: base-nginx.yaml
          service: nginx-product
	    deploy:
          << : *deploy_default
        resources:
		    limits:
			    cpus: '0.50'
			    memory: 500M

    nodeweb:
        extends:
          file: base-nodeweb.yaml
          service: nodeweb-product
	    deploy:
          << : *deploy_default
        resources:
		    limits:
			    cpus: '0.50'
			    memory: 500M

    mongodb:
        restart: always
        extends:
          file: base-mongodb.yaml
          service: mongodb-product
	    deploy:
          << : *deploy_default
        resources:
		    limits:
			    cpus: '0.50'
			    memory: 500M


