- hosts: localhost
  tasks:
    - name: test
      shell: echo "hello world"

- hosts: webservers
  remote_user: ansiblecenter
  become: yes
  become_method: sudo
  
  vars:
    worgkingdir: /statics
  tasks:
    - name: Install nginx web server
      yum: name=nginx state=latest
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted


